---
name: Production heartbeat
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ping_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: KengoTODA/actions-setup-docker-compose@main
        name: Set up Docker Compose
        with:
          version: '2.37.3'

      - name: Decrypt environment file
        run: ./docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}
          ENV_FILE: ${{ secrets.env_file }}

      - name: Ensure that production is alive
        run: ./scripts/ping_production
