---
name: TripIt API Deployment
on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: KengoTODA/actions-setup-docker-compose@main
        name: Set up Docker Compose
        with:
          version: '2.37.3'

      - name: Decrypt environment file
        run: ./docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Run unit tests
        run: ./scripts/unit

  integration_tests:
    needs: [unit_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: KengoTODA/actions-setup-docker-compose@main
        name: Set up Docker Compose
        with:
          version: '2.37.3'

      - name: Decrypt environment file
        run: ./docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Run integration tests
        run: ./scripts/integration

  deploy_to_production:
    needs: [unit_tests, integration_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: KengoTODA/actions-setup-docker-compose@main
        name: Set up Docker Compose
        with:
          version: '2.37.3'

      - name: Decrypt environment file
        run: ./docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Deploy to Production
        run: ./scripts/production

  smoke_test:
    needs: [unit_tests, integration_tests, deploy_to_production]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: KengoTODA/actions-setup-docker-compose@main
        name: Set up Docker Compose
        with:
          version: '2.37.3'

      - name: Decrypt environment file
        run: ./docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Run smoke test
        run: ./scripts/ping_production

